


from fastapi import APIRouter, HTTPException
from github import Github
from config import Config
from utils.logger import Logger
from pydantic import BaseModel
from typing import List, Dict, Any

logger = Logger(__name__)

# Request model (same as in main.py)
class ExportRequest(BaseModel):
    repo_name: str
    files: List[Dict[str, Any]]

class ExportProjectHandler:
    def __init__(self):
        logger.step("Export Project Handler", "initialized")
    
    async def handle(self, repo_name: str, files: list):
        logger.step("GitHub Export", f"started for repo: {repo_name}")
        logger.debug(f"Exporting {len(files)} files")
        
        try:
            g = Github(Config.GITHUB_TOKEN)
            user = g.get_user()
            logger.info(f"Authenticated as GitHub user: {user.login}")
            
            repo = user.create_repo(repo_name, private=True)
            logger.success(f"✅ Repository created: {repo.html_url}")
            
            file_count = 0
            for file in files:
                try:
                    repo.create_file(
                        path=file["path"],
                        message="Generated by Codeless AI",
                        content=file["content"]
                    )
                    file_count += 1
                except Exception as e:
                    logger.error(f"Failed to create file {file['path']}: {str(e)}")
            
            logger.success(f"✅ Created {file_count}/{len(files)} files in repository")
            return {"repo_url": repo.html_url}
            
        except Exception as e:
            logger.error(f"❌ Export error: {str(e)}")
            raise HTTPException(status_code=500, detail=str(e))

handler = ExportProjectHandler()
router = APIRouter(prefix="/api/v1", tags=["export"])

@router.post("/export-project")
async def export_project(request: ExportRequest):
    return await handler.handle(request.repo_name, request.files)