# backend/endpoints/export_project.py
from fastapi import HTTPException
from github import Github
from config import Config
from utils.logger import Logger

logger = Logger(__name__)

class ExportProjectHandler:
    def __init__(self):
        logger.step("Export Project Handler", "initialized")
    
    async def handle(self, repo_name: str, files: list):
        """Handle project export to GitHub"""
        logger.step("GitHub Export", f"started for repo: {repo_name}")
        logger.debug(f"Exporting {len(files)} files")
        
        try:
            # Initialize GitHub client
            g = Github(Config.GITHUB_TOKEN)
            user = g.get_user()
            
            logger.info(f"Authenticated as GitHub user: {user.login}")
            
            # Create repository
            logger.debug(f"Creating repository: {repo_name}")
            repo = user.create_repo(repo_name, private=True)
            logger.success(f"✅ Repository created: {repo.html_url}")
            
            # Create files
            file_count = 0
            for file in files:
                try:
                    repo.create_file(
                        path=file["path"],
                        message="Generated by Codeless AI",
                        content=file["content"]
                    )
                    file_count += 1
                except Exception as e:
                    logger.error(f"Failed to create file {file['path']}: {str(e)}")
            
            logger.success(f"✅ Created {file_count}/{len(files)} files in repository")
            return {"repo_url": repo.html_url}
            
        except Exception as e:
            logger.error(f"❌ Export error: {str(e)}")
            raise HTTPException(status_code=500, detail=str(e))

# Handler instance
handler = ExportProjectHandler()